name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy to GitHub Pages
        run: |
          npm install
          npm run build
          git config --global user.name "rohinipitta"
          git config --global user.email "rohinipitta189@gmail.com"
          git add -A
          git commit -m "Deploy site"
          git push origin gh-pages
